name: Build
on:
  pull_request:
    branches:
      - "1.13"
  push:
    branches:
      - "1.13"

jobs:
  build_windows:
    name: Build windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.13'
        
      - name: Build
        run: go test

  build_linux:
    name: Build linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.13'

      - name: Build
        run: go test
        
  build_darwin:
    name: Build Mac
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.13'

      - name: Build
        run: go test
