name: Build
on:
  push:
    branches:
      - main

jobs:
  build_windows:
    name: Build windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.18-beta1'
        
      - name: Build
        run: go build
        env:
          GOOS: windows
          GOARCH: amd64

  build_linux:
    name: Build linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.18-beta1'

      - name: Build
        run: go build
        env:
          GOOS: linux
          GOARCH: amd64
        
      - name: Build
        run: go build
        env:
          GOOS: linux
          GOARCH: arm64
        
  build_darwin:
    name: Build Mac
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.18-beta1'

      - name: Build
        run: go build
        env:
          GOOS: darwin
          GOARCH: amd64
        
      - name: Build
        run: go build
        env:
          GOOS: darwin
          GOARCH: arm64
